Update pre commit
neutrons/drtsans pull request #607
Opened 2024-12-18 17:28 UTC by backmari

# Short description of the changes:

# Long description of the changes:

# Check list for the pull request
- [ ] I have read the [CONTRIBUTING]
- [ ] I have read the [CODE_OF_CONDUCT]
- [ ] I have added tests for my changes
- [ ] I have updated the documentation accordingly

# Check list for the reviewer
- [ ] I have read the [CONTRIBUTING]
- [ ] I have verified the proposed changes
- [ ] best software practices
    + [ ] all internal functions have an underbar, as is python standard
    + [ ] clearly named variables (better to be verbose in variable names)
    + [ ] code comments explaining the intent of code blocks
- [ ] All the tests are passing
- [ ] The documentation is up to date
- [ ] code comments added when explaining intent

# Manual test for the reviewer

# References

2025-01-29 17:52 UTC, jmborr requested changes
I think you need to undo the changes to the python notebooks because I doubt very much the linters are supposed to change that

2025-02-10 19:42 UTC, backmari commented on tests/integration/drtsans/tof/eqsans/test_simulated_events.py
> -        sample_logs.insert("high_tof_clip", high_tof_clip, unit="ms"),
can the commas at the end be removed?

2025-02-10 19:42 UTC, backmari commented on tests/integration/drtsans/tof/eqsans/test_simulated_events.py
> -        sample_logs.insert("high_tof_clip", high_tof_clip, unit="ms"),
can the commas at the end be removed?

2025-02-10 19:42 UTC, backmari commented on tests/integration/drtsans/tof/eqsans/test_simulated_events.py
> -        sample_logs.insert("high_tof_clip", high_tof_clip, unit="ms"),
can the commas at the end be removed?

2025-02-10 19:42 UTC, backmari commented on tests/unit/drtsans/tof/eqsans/test_transmission.py
> -    clean_workspace(fitting_results.lead_transmission),
can the commas at the end be removed?

2025-02-10 19:42 UTC, backmari commented on tests/unit/drtsans/tof/eqsans/test_transmission.py
> -    clean_workspace(fitting_results.lead_transmission),
can the commas at the end be removed?

2025-02-10 19:59 UTC, backmari reviewed
I have reviewed this PR and approve. However, I can't approve since I opened the PR (but I did none of the work). @jmborr would you mind clicking the approve button for me?

2025-02-11 17:32 UTC, glass-ships approved these changes

2025-02-11 17:32 UTC, merged